// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using DXNewsApp;
using DXNewsApp.Models;
using Microsoft.Rest;

namespace DXNewsApp
{
    public static partial class DXNewsAppClientExtensions
    {
        /// <param name='operations'>
        /// Reference to the DXNewsApp.IDXNewsAppClient.
        /// </param>
        public static IList<NewsItem> GetNews(this IDXNewsAppClient operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IDXNewsAppClient)s).GetNewsAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the DXNewsApp.IDXNewsAppClient.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<IList<NewsItem>> GetNewsAsync(this IDXNewsAppClient operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<System.Collections.Generic.IList<DXNewsApp.Models.NewsItem>> result = await operations.GetNewsWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
        
        /// <param name='operations'>
        /// Reference to the DXNewsApp.IDXNewsAppClient.
        /// </param>
        public static NewsItem LatestNewsItem(this IDXNewsAppClient operations)
        {
            return Task.Factory.StartNew((object s) => 
            {
                return ((IDXNewsAppClient)s).LatestNewsItemAsync();
            }
            , operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
        }
        
        /// <param name='operations'>
        /// Reference to the DXNewsApp.IDXNewsAppClient.
        /// </param>
        /// <param name='cancellationToken'>
        /// Cancellation token.
        /// </param>
        public static async Task<NewsItem> LatestNewsItemAsync(this IDXNewsAppClient operations, CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            Microsoft.Rest.HttpOperationResponse<DXNewsApp.Models.NewsItem> result = await operations.LatestNewsItemWithOperationResponseAsync(cancellationToken).ConfigureAwait(false);
            return result.Body;
        }
    }
}
